# Generated by Django 6.0.4 on 2026-04-13 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Período no formato YYYY-MM (ex: 2025-04)', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('analysis_text', models.TextField(blank=True, default='')),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('net_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise Financeira',
                'verbose_name_plural': 'Análises Financeiras',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'period'], name='ai_financia_user_id_938272_idx')],
            },
        ),
    ]
